[package]
name = "fortuner"
version = "0.1.0"
edition = "2024"

[dependencies]
rand = "0.8"
walkdir = "2"
regex = "1"
anyhow = "1.0.100"
pretty_assertions = "1.4.1"


[dependencies.clap]
version = "4"
features = ["derive", "cargo", "string"]

[dev-dependencies]
assert_cmd = "2"
predicates = "3"
